# Generated by Django 3.2.13 on 2022-07-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
    ]
