# Generated by Django 3.2.13 on 2022-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220705_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_region',
            field=models.CharField(default='', max_length=20),
        ),
    ]
