# Generated by Django 3.2.13 on 2022-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_region',
            field=models.CharField(default='Bristol', max_length=20),
        ),
    ]
