# Generated by Django 3.2.13 on 2022-07-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
