# Generated by Django 3.2.13 on 2022-07-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_region',
        ),
    ]
