# Generated by Django 3.2.13 on 2022-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_post_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
