# Generated by Django 3.2.13 on 2022-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_blurb',
            field=models.CharField(default='..', max_length=100),
            preserve_default=False,
        ),
    ]
