# Generated by Django 3.2.13 on 2022-08-07 18:08

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_profilepicture_profile_image_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('instagram_url', models.CharField(default='placeholder', max_length=150, null=True, unique=True)),
                ('strava_url', models.CharField(default='placeholder', max_length=150, null=True, unique=True)),
                ('linkedin_url', models.CharField(default='placeholder', max_length=150, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
