# Generated by Django 3.2.13 on 2022-08-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220807_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='display_name',
        ),
    ]
