# Generated by Django 3.2.13 on 2022-08-08 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_user_name_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_cairn',
            field=models.CharField(blank='true', choices=[('Pen y Fan', 'Pen y Fan'), ('Corn Du', 'Corn Du'), ('Fan y Big', 'Fan y Big'), ('Fan Brycheiniog', 'Fan Brycheiniog'), ('Pen Cerrig Calch', 'Pen Cerrig Calch'), ('Picws Du', 'Picws Du'), ('Fan Frynych', 'Fan Frynych'), ('Cribyn', 'Cribyn'), ('Mynydd Llangorse', 'Mynydd Llangorse'), ('Skirrid Fawr', 'Skirrid Fawr'), ('Waun Fach', 'Waun Fach'), ('Twmpa', 'Twmpa'), ('Mynydd Troed', 'Mynydd Troed'), ('The Blorenge', 'The Blorenge'), ('ay Bluff', 'ay Bluff'), ('Pen Y Gadair Fawr', 'Pen Y Gadair Fawr'), ('Sugar Loaf', 'Sugar Loaf'), ('Fan Fawr', 'Fan Fawr'), ('Crug Hywel', 'Crug Hywel'), ('Tor Y Foel', 'Tor Y Foel')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='meters_climbed',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='second_cairn',
            field=models.CharField(blank='true', choices=[('Pen y Fan', 'Pen y Fan'), ('Corn Du', 'Corn Du'), ('Fan y Big', 'Fan y Big'), ('Fan Brycheiniog', 'Fan Brycheiniog'), ('Pen Cerrig Calch', 'Pen Cerrig Calch'), ('Picws Du', 'Picws Du'), ('Fan Frynych', 'Fan Frynych'), ('Cribyn', 'Cribyn'), ('Mynydd Llangorse', 'Mynydd Llangorse'), ('Skirrid Fawr', 'Skirrid Fawr'), ('Waun Fach', 'Waun Fach'), ('Twmpa', 'Twmpa'), ('Mynydd Troed', 'Mynydd Troed'), ('The Blorenge', 'The Blorenge'), ('ay Bluff', 'ay Bluff'), ('Pen Y Gadair Fawr', 'Pen Y Gadair Fawr'), ('Sugar Loaf', 'Sugar Loaf'), ('Fan Fawr', 'Fan Fawr'), ('Crug Hywel', 'Crug Hywel'), ('Tor Y Foel', 'Tor Y Foel')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='third_cairn',
            field=models.CharField(blank='true', choices=[('Pen y Fan', 'Pen y Fan'), ('Corn Du', 'Corn Du'), ('Fan y Big', 'Fan y Big'), ('Fan Brycheiniog', 'Fan Brycheiniog'), ('Pen Cerrig Calch', 'Pen Cerrig Calch'), ('Picws Du', 'Picws Du'), ('Fan Frynych', 'Fan Frynych'), ('Cribyn', 'Cribyn'), ('Mynydd Llangorse', 'Mynydd Llangorse'), ('Skirrid Fawr', 'Skirrid Fawr'), ('Waun Fach', 'Waun Fach'), ('Twmpa', 'Twmpa'), ('Mynydd Troed', 'Mynydd Troed'), ('The Blorenge', 'The Blorenge'), ('ay Bluff', 'ay Bluff'), ('Pen Y Gadair Fawr', 'Pen Y Gadair Fawr'), ('Sugar Loaf', 'Sugar Loaf'), ('Fan Fawr', 'Fan Fawr'), ('Crug Hywel', 'Crug Hywel'), ('Tor Y Foel', 'Tor Y Foel')], default='', max_length=20, null=True),
        ),
    ]
